apiVersion: v1
kind: Namespace
metadata:
  name: udemy4-c010-s5-20260724
  labels:
    app.kubernetes.io/part-of: udemy4-c010
    app.kubernetes.io/managed-by: udemy4
    udemy4.example/course: C010
    udemy4.example/lab: section-s5
    udemy4.example/purpose: training
